#! /bin/sh

# Set the cursor
xsetroot -cursor_name left_ptr

# Launch sxhk daemon
sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc $XDG_CONFIG_HOME/sxhkd/bsphk &

# Launch bar and other program
feh --bg-fill /home/lam/data/personal/Pictures/wallpaper/min-LA-city.jpg &
polybar bspwm &

# Desktop name
bspc monitor -d א I II III IV V VI VII VIII IX
 #bspc monitor -d ٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩
 #bspc monitor -d א 1 2 3 4 5 6 7 8 9
bspc monitor eDP1 -d א I II III IV X
bspc monitor DP1 -d V VI VII VIII IX X

# Behaviour
bspc config border_width         	2
bspc config window_gap           	2
bspc config split_ratio          	0.6
bspc config pointer_modifier 		mod1

bspc config borderless_monocle   	false
bspc config gapless_monocle      	true
bspc config paddingless_monocle		true
bspc config single_monocle		    true
bspc config top_padding			    0

# Colour
bspc config normal_border_color 	'#373b41'
bspc config active_border_color 	'#707880'
bspc config focused_border_color 	'#c5c8c6'
bspc config presel_feedback_color 	'#282a2e'

# Rule
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Steam desktop='^8' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
