#! /bin/sh

# Launch sxhk daemon
sxhkd -c $XDG_CONFIG_HOME/sxhkd/{sxhkdrc,bsphk} &

# Launch bar and other program
feh --bg-fill /mnt/shared/Pictures/wallpaper/02.png &
#polybar bspwm &

# Desktop name
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d I II III IV X
#bspc monitor DP1 -d V VI VII VIII IX X

# Behaviour
bspc config border_width         	2
bspc config window_gap           	4
bspc config split_ratio          	0.65
bspc config pointer_modifier 		mod1

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config paddingless_monocle		true
bspc config single_monocle		true
bspc config top_padding			0

# Colour
bspc config normal_border_color 	'#373b41'
bspc config active_border_color 	'#707880'
bspc config focused_border_color 	'#c5c8c6'
bspc config presel_feedback_color 	'#282a2e'

# Rule
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
